require './app'
require 'rack/test'
require 'rdf'
require 'rdf/rdfxml'

include RDF

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration


def app
  Application 
end

def dummy_rdf_file_location
  File.join(File.dirname(__FILE__), '..', 'data', 'test/sample.rdfxml')
end

def dummy_RDF  
  IO.read(dummy_rdf_file_location)
end

def resource_uri
  'http://www.example.com'
end



